language: node_js
node_js:
  - "10"
  - "12"
os:
  - linux
  - osx
install:
  - npm install
script:
  - npm run bundle
  - npm run test:unit
  - npm run test:integration
notifications:
  slack:
    secure: qZDz2sz8H8fjmjzq1SV7jvUkcXFfL6A0Y6aGrJ2iadXIUHeMCnKo46gCTrgCRVfZ99/IiloBcKGCRf1zRRC24Yga9s9WBSA09fflWulSB0+2wEqhAVrBQulMpilEA99whwUhzYzOWgO6kWWrkjuAkw6nHutvCp1v8IPpYFYedzVg3dTnbP5DFcz0fRLL6jc7W5Fdz0aXBzBtfrlhmRy+TmlpxGumw+LTGAy+0FgySJmHYgXEF8yo4QABx8IqE71+vBXQPNaH3je7y42VT3czvRDOmKBjCTzaVO2moXtfkC8KtbR5Vf3g+uOcz5uXynzAw+Ld5wE6U99/O8AfiuG6SKDVfabtHLR3dG6wG0XKgsTCJM9dmGoeszheRBk5ckNxlO7yVld7aoqosag5CWJHGRBZRnY6HonUo7MxARu/1V9wHwmfzdbBV3vGyv6uOvTEvH2GM2LCgd7W/u+poJNr04f3VAQSsbGaiNFrHpMVS5vk+vMRdeNchiQW2w9/EtBL+eCaTJw2XdB4zG/hVDKNrZ3zvYQ0MOzRDQAaLdYKSSUahUvH1H9VGOSMchZdaT6lKqoLa8Fzkv7Uc02wf+VNhzPdh9BJ5Wb/nTvoOdpclyse8OjElQsqafYxlh6pe+BMUIqqS9uJOPKjSBnIZiJFAP+Jx7zWgE+7rr94GsL04HI=
